// Curated event database: famous moments in history, natural disasters,
// space missions, cultural landmarks. Used by the search bar to translate
// natural-language queries into timestamps.
//
// Each event has:
//   name:        display name (shown in the result panel)
//   keywords:    lowercased strings the fuzzy matcher scores against
//   date:        ISO 8601 timestamp (UTC). If time-of-day is unknown, use noon.
//   description: one-line context shown alongside the date
//
// Add events by appending to this array. Order doesn't matter (search scores
// all candidates). Keep keywords specific: "storm" would match too many things.

export const EVENTS = [
    // --- Natural disasters -------------------------------------------------
    { name: 'Hurricane Katrina landfall', keywords: ['katrina', 'hurricane katrina', 'new orleans hurricane'],
      date: '2005-08-29T11:10:00Z', description: 'Hurricane Katrina hits the Gulf Coast, near New Orleans.' },
    { name: 'Hurricane Sandy landfall', keywords: ['sandy', 'hurricane sandy', 'superstorm sandy'],
      date: '2012-10-29T23:30:00Z', description: 'Superstorm Sandy strikes the northeastern US coast.' },
    { name: 'Hurricane Harvey landfall', keywords: ['harvey', 'hurricane harvey'],
      date: '2017-08-26T03:00:00Z', description: 'Hurricane Harvey makes landfall in Texas.' },
    { name: 'Hurricane Maria landfall', keywords: ['maria', 'hurricane maria', 'puerto rico hurricane'],
      date: '2017-09-20T10:15:00Z', description: 'Hurricane Maria devastates Puerto Rico.' },
    { name: 'Hurricane Andrew landfall', keywords: ['andrew', 'hurricane andrew'],
      date: '1992-08-24T09:05:00Z', description: 'Hurricane Andrew hits south Florida.' },
    { name: 'Hurricane Ian landfall', keywords: ['ian', 'hurricane ian'],
      date: '2022-09-28T19:05:00Z', description: 'Hurricane Ian strikes southwest Florida.' },
    { name: '2004 Indian Ocean tsunami', keywords: ['tsunami', 'indian ocean tsunami', 'boxing day tsunami', '2004 tsunami'],
      date: '2004-12-26T00:58:53Z', description: 'Magnitude 9.1 quake off Sumatra triggers a devastating tsunami.' },
    { name: 'Tōhoku earthquake and tsunami', keywords: ['tohoku', 'japan earthquake', 'fukushima', '2011 japan tsunami'],
      date: '2011-03-11T05:46:24Z', description: 'Magnitude 9.1 quake off Japan, triggering the Fukushima disaster.' },
    { name: '2010 Haiti earthquake', keywords: ['haiti earthquake', 'haiti quake', '2010 haiti'],
      date: '2010-01-12T21:53:10Z', description: 'Magnitude 7.0 quake strikes Haiti near Port-au-Prince.' },
    { name: 'Mount St. Helens eruption', keywords: ['mount st helens', 'st helens', 'mount saint helens'],
      date: '1980-05-18T15:32:00Z', description: 'Explosive eruption of Mount St. Helens in Washington state.' },
    { name: 'Krakatoa eruption', keywords: ['krakatoa', 'krakatau'],
      date: '1883-08-27T02:56:00Z', description: 'Catastrophic eruption of Krakatoa in Indonesia.' },
    { name: 'Eyjafjallajökull eruption', keywords: ['iceland volcano', 'eyjafjallajokull', '2010 iceland eruption'],
      date: '2010-04-14T00:00:00Z', description: 'Icelandic eruption that shut down European airspace for days.' },
    { name: '1906 San Francisco earthquake', keywords: ['san francisco earthquake', '1906 earthquake', 'sf quake'],
      date: '1906-04-18T13:12:00Z', description: 'Magnitude 7.9 quake devastates San Francisco.' },
    { name: '2023 Turkey-Syria earthquake', keywords: ['turkey earthquake', 'syria earthquake', 'turkey syria quake'],
      date: '2023-02-06T01:17:35Z', description: 'Twin magnitude 7.8 quakes strike southern Turkey and Syria.' },
    { name: '2022 Tonga eruption', keywords: ['tonga eruption', 'tonga volcano', 'hunga tonga'],
      date: '2022-01-15T04:14:45Z', description: 'Hunga Tonga volcanic eruption sends a shockwave around the world.' },

    // --- Space & astronomy -------------------------------------------------
    { name: 'Apollo 11 Moon landing', keywords: ['apollo 11', 'moon landing', 'first moon landing', 'armstrong moon'],
      date: '1969-07-20T20:17:40Z', description: 'Neil Armstrong and Buzz Aldrin land on the Moon in the Sea of Tranquility.' },
    { name: 'Sputnik 1 launch', keywords: ['sputnik', 'first satellite', 'sputnik 1'],
      date: '1957-10-04T19:28:34Z', description: 'The Soviet Union launches Sputnik 1, the first artificial satellite.' },
    { name: 'Gagarin first orbit', keywords: ['gagarin', 'yuri gagarin', 'first man in space', 'vostok 1'],
      date: '1961-04-12T06:07:00Z', description: 'Yuri Gagarin becomes the first human in space aboard Vostok 1.' },
    { name: 'Apollo 8 Earthrise', keywords: ['earthrise', 'apollo 8', 'first earthrise'],
      date: '1968-12-24T16:39:00Z', description: 'Apollo 8 astronauts photograph Earth rising over the lunar horizon.' },
    { name: 'Voyager 1 launch', keywords: ['voyager 1', 'voyager launch'],
      date: '1977-09-05T12:56:00Z', description: 'NASA launches Voyager 1, now the most distant human-made object.' },
    { name: 'Hubble Space Telescope launch', keywords: ['hubble', 'hubble telescope', 'hubble launch'],
      date: '1990-04-24T12:33:51Z', description: 'Space Shuttle Discovery launches the Hubble Space Telescope.' },
    { name: 'ISS assembly begins', keywords: ['iss', 'international space station', 'iss launch', 'zarya'],
      date: '1998-11-20T06:40:00Z', description: 'First module (Zarya) of the International Space Station launched.' },
    { name: 'Halley\'s Comet 1986 perihelion', keywords: ['halley', 'halleys comet', 'comet halley'],
      date: '1986-02-09T00:00:00Z', description: 'Halley\'s Comet reaches perihelion on its most recent visit.' },
    { name: 'Comet NEOWISE close approach', keywords: ['neowise', 'comet neowise', '2020 comet'],
      date: '2020-07-23T00:00:00Z', description: 'Comet C/2020 F3 NEOWISE at closest approach to Earth.' },
    { name: 'Total solar eclipse (Great American)', keywords: ['great american eclipse', '2017 eclipse', 'august 2017 eclipse'],
      date: '2017-08-21T18:25:00Z', description: 'Total solar eclipse crosses the continental United States.' },
    { name: 'Total solar eclipse April 2024', keywords: ['2024 eclipse', 'april 2024 eclipse', 'north america eclipse'],
      date: '2024-04-08T18:17:00Z', description: 'Total solar eclipse crosses Mexico, US, and Canada.' },
    { name: 'James Webb Space Telescope launch', keywords: ['james webb', 'jwst', 'webb telescope'],
      date: '2021-12-25T12:20:00Z', description: 'JWST launches from French Guiana on an Ariane 5 rocket.' },
    { name: 'Chandrayaan-3 Moon landing', keywords: ['chandrayaan', 'chandrayaan-3', 'chandrayaan 3', 'india moon landing'],
      date: '2023-08-23T12:33:00Z', description: 'India\'s Chandrayaan-3 becomes the first mission to land near the lunar south pole.' },
    { name: 'SpaceX Falcon 9 first landing', keywords: ['spacex first landing', 'falcon 9 landing', 'first reusable rocket'],
      date: '2015-12-22T01:29:00Z', description: 'SpaceX successfully lands a Falcon 9 first stage after orbital launch.' },
    { name: 'Cassini Grand Finale', keywords: ['cassini', 'cassini finale', 'cassini saturn'],
      date: '2017-09-15T11:55:00Z', description: 'Cassini spacecraft ends its mission by plunging into Saturn.' },

    // --- Modern historical -------------------------------------------------
    { name: 'September 11 attacks', keywords: ['9/11', '911', 'september 11', 'twin towers', 'world trade center'],
      date: '2001-09-11T12:46:00Z', description: 'Coordinated terrorist attacks on New York and Washington.' },
    { name: 'Fall of the Berlin Wall', keywords: ['berlin wall', 'fall of berlin wall', 'berlin wall falls'],
      date: '1989-11-09T18:00:00Z', description: 'East Germany opens the Berlin Wall.' },
    { name: 'End of WWII in Europe (VE Day)', keywords: ['ve day', 've day', 'end of wwii europe', 'victory in europe'],
      date: '1945-05-08T00:00:00Z', description: 'Nazi Germany surrenders, ending WWII in Europe.' },
    { name: 'End of WWII (VJ Day)', keywords: ['vj day', 'end of wwii', 'japan surrender'],
      date: '1945-09-02T00:00:00Z', description: 'Japan formally surrenders aboard USS Missouri.' },
    { name: 'Pearl Harbor attack', keywords: ['pearl harbor', 'pearl harbour', 'attack on pearl harbor'],
      date: '1941-12-07T17:48:00Z', description: 'Japanese attack on Pearl Harbor brings the US into WWII.' },
    { name: 'D-Day (Normandy invasion)', keywords: ['d-day', 'dday', 'normandy invasion', 'normandy landings'],
      date: '1944-06-06T06:30:00Z', description: 'Allied forces land on the beaches of Normandy.' },
    { name: 'Titanic sinking', keywords: ['titanic', 'titanic sinks'],
      date: '1912-04-15T05:18:00Z', description: 'RMS Titanic sinks in the North Atlantic after hitting an iceberg.' },
    { name: 'Wright brothers first flight', keywords: ['wright brothers', 'first flight', 'kitty hawk'],
      date: '1903-12-17T15:35:00Z', description: 'The Wright brothers achieve the first powered flight at Kitty Hawk.' },
    { name: 'JFK assassination', keywords: ['jfk assassination', 'kennedy shot', 'kennedy assassination', 'dallas 1963'],
      date: '1963-11-22T18:30:00Z', description: 'President John F. Kennedy is shot in Dallas.' },
    { name: 'MLK assassination', keywords: ['mlk assassination', 'martin luther king shot', 'king assassination'],
      date: '1968-04-04T23:01:00Z', description: 'Martin Luther King Jr. is assassinated in Memphis.' },
    { name: 'Gandhi assassination', keywords: ['gandhi assassination', 'gandhi shot', 'mahatma gandhi death'],
      date: '1948-01-30T11:47:00Z', description: 'Mahatma Gandhi is assassinated in New Delhi.' },
    { name: 'Chernobyl disaster', keywords: ['chernobyl', 'chernobyl disaster', 'chernobyl meltdown'],
      date: '1986-04-26T01:23:45Z', description: 'Reactor 4 at the Chernobyl nuclear plant explodes.' },
    { name: 'Bhopal disaster', keywords: ['bhopal', 'bhopal disaster', 'union carbide bhopal'],
      date: '1984-12-03T00:30:00Z', description: 'Gas leak at Union Carbide plant in Bhopal, India.' },
    { name: 'Nelson Mandela released', keywords: ['mandela released', 'mandela freedom', 'nelson mandela release'],
      date: '1990-02-11T14:00:00Z', description: 'Nelson Mandela walks free after 27 years in prison.' },
    { name: 'COVID-19 pandemic declared', keywords: ['covid pandemic', 'coronavirus pandemic', 'covid 19 declared', 'pandemic declared'],
      date: '2020-03-11T00:00:00Z', description: 'WHO declares COVID-19 a global pandemic.' },
    { name: 'India independence', keywords: ['india independence', 'indian independence', 'india 1947'],
      date: '1947-08-15T00:00:00Z', description: 'India gains independence from British rule.' },
    { name: 'Obama inauguration', keywords: ['obama inauguration', 'obama first inauguration', 'obama sworn in'],
      date: '2009-01-20T17:00:00Z', description: 'Barack Obama is inaugurated as the 44th US President.' },

    // --- Culture & sports --------------------------------------------------
    { name: 'Woodstock festival opens', keywords: ['woodstock', 'woodstock festival'],
      date: '1969-08-15T17:07:00Z', description: 'The Woodstock music festival begins in upstate New York.' },
    { name: 'Beatles arrive in America', keywords: ['beatles ed sullivan', 'beatles america', 'british invasion'],
      date: '1964-02-09T00:00:00Z', description: 'The Beatles perform on The Ed Sullivan Show.' },
    { name: 'Elvis Presley dies', keywords: ['elvis dies', 'elvis death', 'elvis presley death'],
      date: '1977-08-16T20:30:00Z', description: 'Elvis Presley dies at Graceland.' },
    { name: 'FIFA World Cup Final 2022', keywords: ['world cup 2022', 'qatar world cup final', 'messi world cup'],
      date: '2022-12-18T15:00:00Z', description: 'Argentina defeats France in the FIFA World Cup Final in Qatar.' },
    { name: 'Tokyo Olympics 2020 opening', keywords: ['tokyo olympics', 'tokyo 2020', '2021 olympics'],
      date: '2021-07-23T11:00:00Z', description: 'Delayed 2020 Tokyo Olympics opening ceremony (held in 2021).' },
    { name: 'London Olympics 2012 opening', keywords: ['london olympics', '2012 olympics', 'london 2012'],
      date: '2012-07-27T20:12:00Z', description: 'London 2012 Olympics opening ceremony.' },
];
